services:
  - type: web
    name: unmei-navi-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn line_bot:app --bind 0.0.0.0:$PORT

